### PR TITLE
NXP-20856: Add missing contrib in MANIFEST.MF

### PR DESCRIPTION
**Pull request by glefevre**

### CODE REVIEW

**Comment by efge** [comment]
This should have been caught by the tests. Please remove the explicit deploy of `org.nuxeo.ecm.csv:OSGI-INF/csv-importer-service.xml` from the `LocalDeploy` in `TestCSVImporterCreateMode.java` and verify that without your patch it fails but with it it works.

**Comment by efge** [comment]
👍

**Comment by ktouchie** [comment]
`csv-importer-service-with-import-mode.xml` -- No need, that's why I got rid of it

".uuit" -- Honestly not sure. Check with Anahide, I think we did that together.

**Comment by troger** [comment]
The file is still in the sources: https://github.com/nuxeo/nuxeo-csv/blob/fix-NXP-20856-missing-contrib/src/test/resources/OSGI-INF/csv-importer-service-with-import-mode.xml

**Comment by troger** [comment]
> ".uuit" -- Honestly not sure. Check with Anahide, I think we did that together.

It feels not right (to me) to have a component name for a service ending with `uuit` 🤔 
We probably can get rid of it...

**Comment by atchertchian** [comment]
agreed with @troger

**Pull request closed without merging**
